import { defineConfig, type Plugin } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';
import fs from 'node:fs';
import path from 'node:path';

const viteHtmlStringify = ({
  input,
  output,
}: {
  input: string;
  output: string;
}): Plugin => {
  return {
    name: 'stringify-html',
    transformIndexHtml(html) {
      let scriptTag = html.match(/\s+<script[^>]*>(.*?)<\/script[^>]*>/)![0];

      return html
        .replace(scriptTag, '')
        .replace('<!-- RNLTE-SCRIPT-PLACEHOLDER -->', scriptTag);
    },
    closeBundle() {
      const html = fs.readFileSync(path.resolve(input, 'index.html'), 'utf8');

      fs.writeFileSync(output, createTemplate(JSON.stringify(html)));
      fs.rm(input, { recursive: true }, (err) => err && console.error(err));
    },
  };
};

const createTemplate = (html: string) => {
  const types = '{ styles?: string; defaultStyles?: string; content?: string }';
  const regex =
    /(\/\* RNLTE-DEFAULT-STYLE-PLACEHOLDER \*\/|\/\* RNLTE-STYLE-PLACEHOLDER \*\/|<!-- RNLTE-ROOT-PLACEHOLDER -->)/;

  const [p1, p2, p3, p4] = html.split(regex).filter((_, i) => !(i % 2));

  return `// This file is generated. Do not edit this file directly!
   export default ({ styles, defaultStyles, content }: ${types}) => [${p1}", defaultStyles, "${p2}", styles, "${p3}", content, "${p4}].join("");`;
};

const editorPath = path.resolve(__dirname, 'src/components/web-editor');

export default defineConfig({
  plugins: [
    viteSingleFile(),
    viteHtmlStringify({
      input: path.resolve(editorPath, 'dist'),
      output: path.resolve(editorPath, 'index.ts'),
    }),
  ],
  root: editorPath,
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
});
