export const EditorEvent = {
  BLUR: 'blur',
  FOCUS: 'focus',
  PASTE: 'paste',
  INPUT: 'input',
  CHANGE: 'change',
  KEY_UP: 'keyup',
  KEY_DOWN: 'keydown',
  SELECT: 'select',
  PRESS: 'press',
  LONG_PRESS: 'longPress',
} as const;

export const DocumentCommandId = {
  BOLD: 'bold',
  ITALIC: 'italic',
  UNDERLINE: 'underline',
  STRIKE_THROUGH: 'strikeThrough',
  SUBSCRIPT: 'subscript',
  SUPERSCRIPT: 'superscript',
  INSERT_ORDERED_LIST: 'insertOrderedList',
  INSERT_UNORDERED_LIST: 'insertUnorderedList',
  INSERT_HORIZONTAL_RULE: 'insertHorizontalRule',
  INSERT_PARAGRAPH: 'insertParagraph',
  INSERT_HTML: 'insertHTML',
  INSERT_TEXT: 'insertText',
  JUSTIFY_CENTER: 'justifyCenter',
  JUSTIFY_LEFT: 'justifyLeft',
  JUSTIFY_RIGHT: 'justifyRight',
  JUSTIFY_FULL: 'justifyFull',
  FORMAT_BLOCK: 'formatBlock',
  BACK_COLOR: 'backColor',
  FORE_COLOR: 'foreColor',
  FONT_SIZE: 'fontSize',
  FONT_NAME: 'fontName',
  REMOVE_FORMAT: 'removeFormat',
  REDO: 'redo',
  UNDO: 'undo',
  COPY: 'copy',
  CUT: 'cut',
  SELECT_ALL: 'selectAll',
  DELETE: 'delete',
  FORWARD_DELETE: 'forwardDelete',
  INDENT: 'indent',
  OUTDENT: 'outdent',
  DECREASE_FONT_SIZE: 'decreaseFontSize',
  INCREASE_FONT_SIZE: 'increaseFontSize',
  DEFAULT_PARAGRAPH_SEPARATOR: 'defaultParagraphSeparator',
  CREATE_LINK: 'createLink',
  UNLINK: 'unlink',
  INSERT_IMAGE: 'insertImage',
  STYLE_WITH_CSS: 'styleWithCSS',
} as const;

export const InnerDocumentCommandId = {
  INSERT_STYLE: 'insertStyle',
  FOCUS: 'focus',
  SELECT: 'select',
  SET_ATTRIBUTE: 'setAttribute',
} as const;
